// This file reads environment variables for almost everything.
// You can use heroku config variables to take advantage of that.
// Do not edit this file, just configure your environment.
// If you are not using Heroku set environment variables via a
// shell script

var settings = module.exports = {
  // HTTP port number for this whereabouts server
  port: process.env.PORT ? process.env.PORT : 3000,
  // HTTP hostname for this whereabouts server
  site: process.env.SITE ? process.env.SITE : 'localhost',
  // AUTHENTICATION DOMAIN - this is your gmail domain, not necessarily the
  // site name of this whereabouts server
  domain: process.env.DOMAIN ? process.env.DOMAIN : 'example.com',
  db: {
    url: process.env.MONGODB_URI ? process.env.MONGODB_URI : 'whereabouts',
  },

  // Hard satuses should be a comma-separated list in HARD_STATUSES, otherwise our defaults  
  hardStatuses: process.env.HARD_STATUSES ? process.env.HARD_STATUSES.split(',') : ['Available', 'In a Meeting', 'Unavailable', 'At Lunch']
};

// For Heroku, Stagecoach and other reverse proxies, this should be 
// overridden to 80 via PUBLIC_PORT
settings.publicPort = process.env.PUBLIC_PORT ? process.env.PUBLIC_PORT : settings.port;

// Teams should be in variables TEAM_1, TEAM_2, etc. and be comma-separated
// lists of usernames 

settings.teams = {};
var n = 1;
while(true) {
  var name = 'TEAM_' + n;
  if (process.env[name]) {
    var teamGuts = process.env[name].split(':');
    var teamName = teamGuts[0];
    var members = teamGuts[1];
    settings.teams[teamName] = members.split(',');
  } else {
    // Once we stop seeing consecutive TEAM_n environment variables we're done
    break;
  }
  n++;
}

if (n === 1) {
  // We didn't find any teams in the env, use the demo team
  settings.teams = {
    marxBros: [ 'chico', 'harpo', 'groucho', 'zeppo' ]
  };
}

// Push down any app level settings the model layer should also know about,
// do any other massaging of the configuration that is convenient to do
// before it is accessed by other code

settings.db.domain = settings.domain;

settings.auth = {
  validUser: '*@' + settings.domain,
  google: {
    returnURL: 'http://' + settings.site + ':' + settings.publicPort + '/auth/google/callback',
    realm: 'http://' + settings.site + ':' + settings.publicPort + '/'
  }
};


